// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserPoint = "user_points"

// UserPoint ⽤户积分汇总表
type UserPoint struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                      // 主键ID
	UserID      int64          `gorm:"column:user_id;not null;comment:⽤户ID" json:"user_id"`                                 // ⽤户ID
	Points      int64          `gorm:"column:points;comment:当前可⽤积分" json:"points"`                                          // 当前可⽤积分
	PointsTotal int64          `gorm:"column:points_total;comment:累计获得积分" json:"points_total"`                              // 累计获得积分
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName UserPoint's table name
func (*UserPoint) TableName() string {
	return TableNameUserPoint
}
