// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserPointsTransaction = "user_points_transactions"

// UserPointsTransaction ⽤户积分明细表
type UserPointsTransaction struct {
	ID             int64 `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                 // 主键ID
	UserID         int64 `gorm:"column:user_id;not null;comment:⽤户ID" json:"user_id"`                            // ⽤户ID
	PointsChange   int64 `gorm:"column:points_change;not null;comment:积分变动值 (正数为增加，负数为扣除)" json:"points_change"` // 积分变动值 (正数为增加，负数为扣除)
	CurrentBalance int64 `gorm:"column:current_balance;not null;comment:当前余额" json:"current_balance"`            // 当前余额
	/*
		交易类型(1:签到 2:连续签到 3:补签 4:每⽇任务
		5:福利任务)
	*/
	TransactionType int32          `gorm:"column:transaction_type;not null;comment:交易类型(1:签到 2:连续签到 3:补签 4:每⽇任务\n5:福利任务)" json:"transaction_type"`
	Description     string         `gorm:"column:description;comment:积分变动说明" json:"description"`                                // 积分变动说明
	ExtJSON         string         `gorm:"column:ext_json;not null;comment:扩展字段" json:"ext_json"`                               // 扩展字段
	CreatedAt       time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt       time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName UserPointsTransaction's table name
func (*UserPointsTransaction) TableName() string {
	return TableNameUserPointsTransaction
}
