// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserMonthlyBonusLog = "user_monthly_bonus_log"

// UserMonthlyBonusLog ⽤户⽉度连续签到奖励记录表
type UserMonthlyBonusLog struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                               // 主键ID
	UserID      int64          `gorm:"column:user_id;not null;comment:⽤户ID" json:"user_id"`                                          // ⽤户ID
	YearMonth   string         `gorm:"column:year_month;not null;comment:年⽉（YYYYMM）" json:"year_month"`                              // 年⽉（YYYYMM）
	BonusType   int32          `gorm:"column:bonus_type;not null;comment:奖励类型（1:连续签到3天 2:连续签到7天 3:连续签到15天 4:⽉满签）" json:"bonus_type"` // 奖励类型（1:连续签到3天 2:连续签到7天 3:连续签到15天 4:⽉满签）
	Description string         `gorm:"column:description;comment:积分变动说明" json:"description"`                                         // 积分变动说明
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`          // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`          // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                             // 删除时间
}

// TableName UserMonthlyBonusLog's table name
func (*UserMonthlyBonusLog) TableName() string {
	return TableNameUserMonthlyBonusLog
}
