// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserinfo = "userinfo"

// Userinfo ⽤户基本信息表
type Userinfo struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                      // 主键ID
	UserID    int64          `gorm:"column:user_id;not null;comment:⽤户ID" json:"user_id"`                                 // ⽤户ID
	Username  string         `gorm:"column:username;not null;comment:⽤户名" json:"username"`                                // ⽤户名
	Password  string         `gorm:"column:password;not null;comment:⽤户密码(bcrypt 加密)" json:"password"`                    // ⽤户密码(bcrypt 加密)
	Email     string         `gorm:"column:email;comment:⽤户邮箱" json:"email"`                                              // ⽤户邮箱
	Avatar    string         `gorm:"column:avatar;comment:⽤户头像" json:"avatar"`                                            // ⽤户头像
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName Userinfo's table name
func (*Userinfo) TableName() string {
	return TableNameUserinfo
}
