// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserCheckinRecord = "user_checkin_records"

// UserCheckinRecord 签到记录表
type UserCheckinRecord struct {
	ID                int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:记录ID" json:"id"`                        // 记录ID
	UserID            int64          `gorm:"column:user_id;not null;comment:⽤户ID" json:"user_id"`                                   // ⽤户ID
	CheckinDate       time.Time      `gorm:"column:checkin_date;not null;comment:签到⽇期" json:"checkin_date"`                         // 签到⽇期
	CheckinType       int32          `gorm:"column:checkin_type;not null;default:1;comment:签到类型：1=正常签到，2=补签" json:"checkin_type"`   // 签到类型：1=正常签到，2=补签
	PointsAwardedBase int32          `gorm:"column:points_awarded_base;not null;default:1;comment:获得积分" json:"points_awarded_base"` // 获得积分
	CreatedAt         time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`   // 创建时间
	UpdatedAt         time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`   // 更新时间
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                      // 删除时间
}

// TableName UserCheckinRecord's table name
func (*UserCheckinRecord) TableName() string {
	return TableNameUserCheckinRecord
}
